# Generated by Django 3.2.8 on 2021-10-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211026_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review_title',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
